### ISSUE TITLE
ember-cli-postcss does not work with JIT

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-sample-apps/tailwind-example#1]
I think the recommended way to use tailwind should be to also use tailwind's recommendations, which can be done via `npx ember-apply tailwind`

Issue reports:
 https://github.com/jeffjewiss/ember-cli-postcss/issues/765
https://github.com/jeffjewiss/ember-cli-postcss/issues/714
https://github.com/embroider-build/embroider/issues/688
https://github.com/embroider-build/embroider/issues/729

Docs to solution:
https://github.com/NullVoxPopuli/ember-apply

**Comment by MelSumner** [comment]
would this eliminate use of `@apply` ?

**Comment by NullVoxPopuli** [comment]
naw. you'd tweak the generated config to use: https://tailwindcss.com/docs/using-with-preprocessors

which is still a separate process to `ember s`, (which you can solve with `concurrently` or `npm-run-all`)

**Comment by NullVoxPopuli** [comment]
Gonna close this. folks should not use ember-cli-postcss these days. 

Instead, use webpack (or vite) native plugins: https://discuss.emberjs.com/t/ember-modern-css/19614
